add types for stores
sveltejs/sapper pull request #1601
Opened 2020-10-13 04:22 UTC by TheComputerM

Fixes https://github.com/sveltejs/sapper/issues/1556
### Before submitting the PR, please make sure you do the following
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
-  [x] Run the tests with `npm test` and lint the project with `npm run lint`

2020-10-13 04:24 UTC, TheComputerM commented on runtime/index.d.ts
> +	export { PageContext as Page } from '@sapper/app/types';
Also imported PageContext from `@sapper/app/types` as to not re-declare it.

2020-10-13 06:13 UTC, ehrencrona approved these changes
LGTM :)

2020-10-13 09:28 UTC, bjon commented
`import { PageContext } from "@sapper/app/types";` doesn't seem to work with vscode. It still shows:
```
(alias) stores(): {
    preloading: Readable<boolean>;
    page: Readable<any>;
    session: Writable<any>;
}
import stores
```

2020-10-13 09:46 UTC, bjon commented
server.ts is created like this:
```
polka() // You can also use Express
	.use(
		compression({ threshold: 0 }),
		sirv('static', { dev }),
		sapper.middleware()
	)
	.listen(PORT, err => {
		if (err) console.log('error', err);
	});

```
so `opts` in middleware, should be optional. 

`export function middleware(opts?: MiddlewareOptions): Handler;`

2020-10-13 09:56 UTC, TheComputerM commented
> `import { PageContext } from "@sapper/app/types";` doesn't seem to work with vscode. It still shows:
> 
> ```
> (alias) stores(): {
>     preloading: Readable<boolean>;
>     page: Readable<any>;
>     session: Writable<any>;
> }
> import stores
> ```

I think PageContext has to be a type instead of an interface for this to work, please correct me if I am wrong.

2020-10-13 10:04 UTC, bjon commented
@TheComputerM Both type or interface should work. I just don't understand the "magic" behind `@sapper/app/types`. 
How can vscode access it?

2020-10-13 10:09 UTC, TheComputerM commented
So, shall I convert `@sapper/app/types` to `./src/app/types`?

2020-10-13 10:30 UTC, bjon commented
That file doesn't exist either?

The only way I can get it to work, is to declare the namespace, directly in the index.d.ts
```
declare module '@sapper/app/types' {
  export interface PageContext {
    host: string;
    path: string;
    params: Record<string, string>;
    query: Record<string, string | string[]>;
    error?: Error;
  }
}
```

But now we're back to square one again :)

2020-10-13 10:37 UTC, TheComputerM commented
This is the [file](https://github.com/sveltejs/sapper/blob/5f4097a870e11b05a13e485e824ea73bebc53908/runtime/src/app/types.ts)

2020-10-13 10:47 UTC, bjon commented
Yes, but only in the source. I can't find it anywhere in `node_modules/sapper` or `src/node_modules/@sapper`.

If its not included in the sapper dist, or auto-generated @sapper, I dont see how we can import it.

2020-10-13 10:51 UTC, TheComputerM commented
So how do we fix this?

2020-10-13 10:57 UTC, bjon commented
If `@sapper/app/types`  and `@sapper/internal/manifest-server` are supported to work, it might be a bug when sapper generate the code?

2020-10-13 10:58 UTC, bjon commented
One workaround would be to add
```
declare module '@sapper/app/types' {
  export interface PageContext {
    host: string;
    path: string;
    params: Record<string, string>;
    query: Record<string, string | string[]>;
    error?: Error;
  }
}
```
and remove it, when the import works?

2020-10-13 11:00 UTC, bjon commented
But im no expert here. I just want auto-complete to work :)

2020-10-13 11:00 UTC, TheComputerM commented
Ok, If someone approves this, I will add this.

2020-10-13 11:02 UTC, bjon commented
And also, `export function start(opts: { target: Node }): Promise<void>;` should be `export function start(opts: { target: Element }): Promise<void>;`, cause `document.querySelector` returns an `Element`
```
sapper.start({
  target: document.querySelector(`#sapper`),
});
```

2020-10-13 11:18 UTC, bjon commented
To avoid compile error its should probably be `export function start(opts: { target: Element | null }): Promise<void>;`.
`document.querySelector` returns `Element | null`

2020-10-13 11:49 UTC, AnandChowdhary commented
> To avoid compile error its should probably be `export function start(opts: { target: Element | null }): Promise<void>;`.
> `document.querySelector` returns `Element | null`
> 
> or maybe better, change sapper-template to convert TS to
> 
> ```
> sapper.start({
>   target: document.querySelector(`#sapper`) as Element,
> });
> ```

This is what we do, maybe it's better to ensure it exists instead of typecasting?

```ts
const target = document.querySelector("#sapper");

if (target)
  sapper.start({
    target,
    hydratable: true,
  });
```

2020-10-13 20:36 UTC, bjon commented
Found one more. In `@sapper/app` goto(opts), should be optional

2020-10-15 08:43 UTC, ehrencrona commented
I looked into how the types work: in the `tsconfig.json` `@sapper` is defined as an alias for the directory `runtime/src`:

```
"paths": {
	"@sapper/*": ["runtime/src/*"]
}
```

This is the reason why `@sapper/internal` references work in Sapper code, but not in project code. In project code there simply is no such thing; the only thing resolved under `@sapper` is what we put in the `index.d.ts`.

Therefore, those references from `index.d.ts` to `@sapper/internal` must be removed. I created #1604 for this. Once that is merged, it should be possible to apply this PR on top of those changes (though I'm afraid that PR might cause some controversy and could take time to merge).

2020-10-15 08:50 UTC, ehrencrona commented
On the discussion around whether `target` in `start` is `Node` or an `Element`: An `Element` *is* a `Node`; `Node` is the most abstract class. `start` can handle `Node`s so it should be `target: Node`.

Furthermore, I don't think `start` can handle `target` being `null`. If you can't find the DOM node you want to start the app in, that's an error, which is essentially what the type mismatch says.

2020-10-21 06:17 UTC, bencates reviewed
Might be nice to parameterize these types to let users type the session and preloaded props.

2020-10-21 06:17 UTC, bencates commented on runtime/index.d.ts
> +	};
```suggestion
	export function stores<Session = any>(): {
		preloading: Readable<boolean>
		page: Readable<PageContext>
		session: Writable<Session>
	};
```

2020-10-21 06:17 UTC, bencates commented on runtime/index.d.ts
> +	export function middleware(opts?: MiddlewareOptions): Handler;
```
	export interface MiddlewareOptions<Session = unknown> {
		session?: (req: Req, res: Res) => Session
		ignore?: Ignore
	}
```

then

```suggestion
	export function middleware<Session = unknown>(opts?: MiddlewareOptions<Session>): Handler;
```

2020-10-21 06:17 UTC, bencates commented on runtime/index.d.ts
>  	}
```
	export interface Preload<Props = object, Session = any> {
		(this: PreloadContext, page: PageContext, session: Session): Props | Promise<Props>;
	}
```

2020-10-23 16:00 UTC, benmccann commented
@TheComputerM this PR will need to be rebased

2020-10-23 17:44 UTC, bencates requested changes
Sorry, this might be my fault. GitHub would only allow me to format half of my proposed changes as suggestions.

2020-10-23 17:44 UTC, bencates commented on runtime/index.d.ts
> +	export function middleware<Session = unknown>(opts?: MiddlewareOptions<Session>): Handler;
I don't think this works correctly unless we also parameterize `MiddlewareOptions`

2020-10-26 04:49 UTC, benmccann commented on runtime/index.d.ts
> +	import { PageContext } from '@sapper/app/types';
`PageContext` is defined lower down in this file in `@sapper/common`

2020-10-26 05:00 UTC, merged